title: Usable Security and Privacy Conference Deadlines
description: Countdowns to Usable Security and Privacy conference deadlines

domain: "usec-deadlines.github.io"
baseurl: ""

github_username: usec-deadlines
github_repo: usec-deadlines.github.io

markdown: kramdown

